"""empty message

Revision ID: 4758f50daea0
Revises: 1b17062ca70c
Create Date: 2022-07-27 12:05:30.447076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4758f50daea0'
down_revision = '1b17062ca70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserBookSuggestions', sa.Column('book_author', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'UserBookSuggestions', ['book_author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserBookSuggestions', type_='unique')
    op.drop_column('UserBookSuggestions', 'book_author')
    # ### end Alembic commands ###
